### ISSUE TITLE
[Q] can you convert it to css so that can be added to ddwrt...

### ISSUE THREAD

**Issue by Mile-Lile** [style-it-themes/dd-wrt-inspired-themes#1]
### Describe the feature you'd like

BS is willing to add it to ddwrt if you can covert it to css

### Additional context

no additional context:)

**Comment by the-j0k3r** [comment]
Hello, and thanks for reaching out. =)

First make sure Brainslayer knows how appreciated that offer is. Its great to get some recognition

This style compiles to down to CSS, anyone could grab the resulting CSS and do that. However its not as simple as just converting it and adding another CSS file or five.

To truly have a 1:1 official DD-WRT would have include the custom checkboxes/inputs/icons modernized redesigns of icons e.g. I use SVG icons, DD-WRT uses old gifs. Logos and any graphics all need to be redone, so you dont see the white edges when over specific dark background colors, the most obvious are the hotspot logos.

DD-WRT uses a oversimplified number of CSS classes, I had to pick at other inline portion to be able to target specific portions in order to be able to distinguish between certain elements like e.g. this `[name='add_button']:not([onclick*='_add'])` a long dance is done all over this project to make this style possible.

As well as the above, any user customizable options would be 100% lost in any process of including any 1 single color schemes as a simple CSS theme.

The current approach that DD-WRT uses for dark themes would need a considerable overall in order to be anywhere ready for actually to get something that looks like this as a end result and is as comprehensive and detailed thoughout all areas. (the details are important to me).
 
**TL;DR**

I wouldn't mind the challenge of improving the built in themes add new ones, extend classes add modern graphics and dig though source code to make it happen, some collaboration/dialog with BrainSlayer and perhaps other people involved with DD-WRT like @egc112, Work like this would take many many hours maybe even months who knows how long this piece of string really is (since this is done on spare time for me). Some real time dialog would probably be needed at some stage.

SVN is a big obstacle for resolving any arising conflicts between edited files and actual live changes (if any) and seeing on the fly any submitted changes spotting any issues visually before they are committed, this would slow down further this work considerably in my experience.

Other words (sorry for rambling)

Why I did this style as is, 3 months of ON/OFF development and ready for consumption.

I hope though anyone that _stumbles_ on this style, doesn't mind installing Stylus and this style to enjoy the work in the meanwhile like detailed in the readme https://github.com/style-it-themes/dd-wrt-inspired-themes#installing

And thanks again for reaching out.

**Comment by the-j0k3r** [comment]
Hello, and thanks for reaching out. =)

First make sure @BrainSlayer knows how appreciated that offer is. Its great to get some recognition.

This style compiles to down to CSS, anyone could grab the resulting CSS and do that (this is MIT license). However its not as simple as just converting it and adding another CSS file or five.

To truly have a 1:1 official DD-WRT would have include the custom checkboxes/inputs/icons modernized redesigns of icons e.g. I use SVG icons, DD-WRT uses old gifs. Logos and any graphics all need to be redone, so you dont see the white edges when over specific dark background colors, the most obvious are the hotspot logos.

DD-WRT uses a oversimplified number of CSS classes, I had to pick at other inline portion to be able to target specific portions in order to be able to distinguish between certain elements like e.g. this `[name='add_button']:not([onclick*='_add'])` a long dance is done all over this project to make this style possible.

As well as the above, any user customizable options would be 100% lost in any process of including any 1 single color schemes as a simple CSS theme.

The current approach that DD-WRT uses for dark themes would need a considerable overall in order to be anywhere ready for actually to get something that looks like this as a end result and is as comprehensive and detailed thoughout all areas. (the details are important to me).
 
**TL;DR**

I wouldn't mind the challenge of improving the built in themes add new ones, extend classes add modern graphics and dig though source code to make it happen, some collaboration/dialog with @BrainSlayer and perhaps other people involved with DD-WRT like @egc112, Work like this would take many many hours maybe even months who knows how long this piece of string really is (since this is done on spare time for me). Some real time dialog would probably be needed at some stage.

SVN is a big obstacle for resolving any arising conflicts between edited files and actual live changes (if any) and seeing on the fly any submitted changes spotting any issues visually before they are committed, this would slow down further this work considerably in my experience.

Other words (sorry for rambling)

Why I did this style as is, 3 months of ON/OFF development and ready for consumption, Some small way to give back to the community and BS for the tireless work he does on DDWRT. Kudos.

I hope though anyone that _stumbles_ on this style, doesn't mind installing Stylus and this style to enjoy the work in the meanwhile like detailed in the readme https://github.com/style-it-themes/dd-wrt-inspired-themes#installing

And thanks again for reaching out.

**Comment by BrainSlayer** [comment]
>
> Hello, and thanks for reaching out. =)
>
> First make sure @BrainSlayer knows how appreciated that offer is. Its great to get some recognition.

i'm BrainSlayer :-)
>
> This style compiles to down to CSS, anyone could grab the resulting CSS and do that. However its not as simple as just converting it and adding another CSS file or five.

i know. but if i at least have a possibility to generate the css, i can make all adjustments manually. but i'm not experienced with css that much. most of the styles are contributions.
>
> To truly have a 1:1 official DD-WRT would have include the custom checkboxes/inputs/icons modernized redesigns of icons e.g. I use SVG icons, DD-WRT uses old gifs . Logos and any graphics all need to be redone, so you dont see the white edges when over specific dark background colors, the most obvious are the hotspot logos.

i do not use gif. i use png. but doesnt make a difference. not scalable
>
> DD-WRT uses a oversimplified number of CSS classes, I had to pick at other inline portion to be able to target specific portions in order to be able to distinguish between certain elements like e.g. this [name='add_button']:not([onclick*='_add']) a long dance is done all over this project to make this style possible.
>
> As well as the above, any user customizable options would be 100% lost in any process of including any 1 single color schemes as a simple CSS theme.
>
> The current approach that DD-WRT uses for dark themes would need a considerable overall in order to be anywhere ready for actually to get something that looks like this as a end result and is as comprehensive and detailed thoughout all areas. (the details are important to me).

the dark style is basicly a additional css style which is placed into the header once its activated. all done by the C cgi web code.
>
> TL;DR
>
> I wouldn't mind the challenge of improving the built in themes add new ones, extend classes add modern graphics and dig though source code to make it happen, some collaboration/dialog with BrainSlayer and perhaps other people involved with DD-WRT like @egc112, Work like this would take many many hours maybe even months who knows how long this piece of string really is (since this is done on spare time for me). Some real time dialog would probably be needed at some stage.
i'm available almost all day by email, but in worst case also with phone or skype, whatsapp. whatever. timezone needs to be considered of course since i'm located in germany
>
> SVN is a big obstacle for resolving any arising conflicts between edited files and actual live changes (if any) and seeing on the fly any submitted changes spotting any issues visually before they are committed, this would slow down further this work considerably in my experience.

there are some hidden features in dd-wrt. if you place a new file in the file system at / it will be used if its a new file which is not defined by the normal webfile set.
this can be used for adding new unknown styles.

so create /style/mystyle/style.css in the filesystem
then create a folder /www/style/mystyle (just the folder)

then your new style shows up on the selection and can be tested

i did not test this for long time of course :-)
the read from the root path is also a  bug. normally it should be /www of course. i will fix this usually in next release. so you can do it directly also in a better way
since the fs is readonly you need to extract and replace it of course. but there is a dirty trick

mkdir /tmp/mywww
mount --bind /tmp/mywww /www

so you can use scp and upload it to the tmp/mywww folder
>
> Other words (sorry for rambling)
>
> Why I did this style as is, 3 months of ON/OFF development and ready for consumption, Some small way to give back to the community and BS for the tireless work he does on DDWRT. Kudos.
i like if people talk to my as third person :-)
>
> I hope though anyone that stumbles on this style, doesn't mind installing Stylus and this style to enjoy the work in the meanwhile like detailed in the readme https://github.com/style-it-themes/dd-wrt-inspired-themes#installing
>
> And thanks again for reaching out.

**Comment by the-j0k3r** [comment]
>i'm BrainSlayer :-)

Indeed =) thanks  for all your work on DD_WRT

>i know. but if i at least have a possibility to generate the css, i can make all adjustments manually. but i'm not experienced with css that much. most of the styles are contributions.

This is semi easy... Assuming you have Stylus and this style installed.

Im sure you know this but here it is.
Open the browser inspector Im using Firefox mostly so its `ctrl+shiif+i` and choose the Style editor tab

Navigating around the files on my end the main compiled CSS it shows up as  <inline style sheet #5>, this may vary but the main has 237 rules (see gif)

![ddwrtcss](https://user-images.githubusercontent.com/31389848/131987117-644f3d64-bf28-49f7-9d67-374449419505.gif)

The name could vary but you get the idea, I hope.

For other sections other inline style sheets are used like e.g oid search, speedchecker and so on. these are equally as important as main style, so as to ensure consistency throughout.

Here is a gist of that compiled CSS (as the animation shows) https://gist.github.com/the-j0k3r/26e7b9d974c12231f234f3bac44ce085 for example =)

But just as is, you may actually get a single color style and you lost all custom stuff and despite all svgs being optimized and being as small as possible, the overall result may increase slighly the overall size because Im inlining all SVG code and base64 encode replaced pngs

>the dark style is basicly a additional css style which is placed into the header once its activated. all done by the C cgi web code.

Above my head slightly cgi/C but I think I get some idea.

>i do not use gif. i use png. but doesnt make a difference. not scalable

I see many gifs dotted around =), indeed mostly I replaced pngs e.g. ddwrt.css has many for instance, I think default.css also shows some. I do prefer svgs mostly because scalability and easy to recolor in styles/projects like this.

![Capture](https://user-images.githubusercontent.com/31389848/131988257-9b18d68a-da6c-4c3d-b6b5-8a96c3e1f630.PNG)

Some of those gifs are just inverted with css filters and hacks to pngs etc use other CSS trickery.

Graphic design, CSS, HTML and what not is not problem, One of the may technologies I work with in RL.

If you havent already installed Stylus and this style, I recommend you do and do play around with the custom options colors and bilt ins styles, each color scheme results in same :root color values changes, which makes a new color scheme.
Possibilities many.

![ddwrtanim](https://user-images.githubusercontent.com/31389848/131990969-07e85488-c7be-458e-ba0f-83febb4448a0.gif)

![ddwrtanim](https://user-images.githubusercontent.com/31389848/131992577-37d5444f-da2d-405e-9d77-e0beebf0a9ac.gif)

And so on.

**Comment by the-j0k3r** [comment]
Also note that margin padding and other such tweaks are new or override the default blue style values or the default CSS that has them,

Some values are added and some override existing in these properties types. as a standalone CSS the end result may need adjusting depending on whats going on.

In addition dd-wrt has many inline color properties which makes any built in themes that have CSS files harder to override e.g.

https://github.com/style-it-themes/dd-wrt-inspired-themes/blob/75a62bc149a20e5bc1903417be2e2b26d569c20a/dd-wrt-inspired-themes.user.styl#L773

Such inline colors should be replaced by some new css class, so that any existing themes/new themes can properly style all areas for consistency sake, even if they can be overridden like Ive done in such cases, its really a bane of styling with CSS alone, dd-wrt isnt alone in this, many more modern websites use them still. the more ppl work on same website the worst it becomes.

This is why built in styles dont actually style consistently and one of the main drivers for this project.

I recommend some care is payed in the examples given, for best results that is.

**Comment by BrainSlayer** [comment]
i found some bugs. if i enable the stylus. i cannot click on the status tab anymore

**Comment by the-j0k3r** [comment]
>i found some bugs. if i enable the stylus. i cannot click on the status tab anymore

@BrainSlayer thanks for that report however;

This style doesn't affect such things or even attempt to alter such functionality. And Stylus even less. So its a little weird

Tested it on Edge chromium  93.0.961.38 (Official build) (64-bit)
Firefox 91.0.2 (64-bit)
OS: Windows 10 pro 2004

What browser are you using and browser version?
Stylus version?

Operative system? Just in case so I can test similar setup.

Also ensure you're not using the CSS file I provided above and you followed the install instructions
https://github.com/style-it-themes/dd-wrt-inspired-themes#installing

Proof below.

![bugs](https://user-images.githubusercontent.com/31389848/132084841-2c06c582-b14b-47e7-b8b4-dc935c175bf0.gif)

pinging some Stylus devs for feedback.

@eight04 @mottie

**Comment by BrainSlayer** [comment]
try it in windows chrome. i works only on the left corner of the button. 80% of the space of that tab does not work. if i double click on that non working area it selects the wan ip information text on the top right corner. 
![image](https://user-images.githubusercontent.com/7693971/132085176-e58ce6b1-2968-4468-b99e-c9a78759b8ed.png)

**Comment by Mile-Lile** [comment]
![Record_select-area_20210904083206](https://user-images.githubusercontent.com/12752816/132085273-46f41137-765f-4f1a-9633-721dfdb75791.gif)

I tried it on Chrome Version 91.0.4472.114 (Official Build) (64-bit) with Linux 5.12.18-amd64-desktop and works very nice... sorry about gif low quality... but havn't figured out how you change these colors... yet :)

**Comment by BrainSlayer** [comment]
i just tried it with windows and in windows it doesnt work. btw. i found a way to convert the stylus code straight to dd-wrt compatible css code. easy task. just dumped it from the chrome dev menu since stylus just injects a css element and nothing else

**Comment by Mile-Lile** [comment]
great news!! maybe ddwrt members could propose "styles" to be included in official ddwrt builds... and contribute this way... On lichess.org members makes these styles for chess pieces  and dev sometimes include these...

**Comment by the-j0k3r** [comment]
> i just tried it with windows and in windows it doesnt work.

I think I see the issue, its only visible in chrome and when the style option to display theme name/version is enabled.

Please disable show style details as follows

![bugs](https://user-images.githubusercontent.com/31389848/132085671-7c18caf3-0d5a-410d-9a56-c266c6d9fb56.gif)

I will dig deeper into this and make the option not default to start with because google chrome is being a ****

> btw. i found a way to convert the stylus code straight to dd-wrt compatible css code. easy task. just dumped it from the chrome dev menu since stylus just injects a css element and nothing else

yes I did describe that method above

https://github.com/style-it-themes/dd-wrt-inspired-themes/issues/1#issuecomment-912430346

However whatever colors/options you have seleted is what the end result will be using that method.
So for every color/settings you have a different compiled CSS, make sense?

However you will need more than just that stylesheet for full effect you need the stylesheet for OID search/speedchecker and so on, else those areas wont be styled.

So you will be missing at least iplookup stylesheet/speedchecker/oidsearch and these stylesheets will only compile if Im not mistaken when you are in respective tabs

**Comment by the-j0k3r** [comment]
>great news!! maybe ddwrt members could propose "styles" to be included in official ddwrt builds... and contribute this way... On lichess.org members makes these styles for chess pieces and dev sometimes include these...

Using the method of grabbing the stylesheets as compiled, they will be much MUCH bigger than any of the existing css.
Just for main areas you have 55KB alone this is without the stylesheets for iplookup stylesheet/speedchecker/oidsearch

So that will add some weight.

I would rather that the complete style is added for all areas not just main because otherwise it breaks the end results.

**Comment by BrainSlayer** [comment]
i know. that only small differences are in between that. i will take care about this. now i'm just testing if everything works. step 2 is shrinking everything to death

**Comment by the-j0k3r** [comment]
@BrainSlayer fixed issue https://github.com/style-it-themes/dd-wrt-inspired-themes/commit/7e803731eff76d4766a4b98214e6fc515671ff8e

Theres two ways to update the style now (since you edited your style to add your IP) the autoupdates are blocked.

1) force update style
2) re-edit IP's

or 

1) copy and paste fix into the same area

> step 2 is shrinking everything to death

hahaha, Im ok with death as long as it doesn't kill the quality.
All images in base64/svgs included are already optimized to death maybe a little more is possible, also, if you minify the css I think it will help some except it wont be human readable anymore, which is OK for the final purposes.

**Comment by BrainSlayer** [comment]
i simply removed the manipulated string. thats a bad idea anyway. i show the copyright information in the selection area for the stylus preset. you will see it when its done. i have already written the code and now i'm just tested it on my devices. auto updates shall not be permitted anyway for security reasons. i have to update the stylus compiled code manually once there is a new one out

**Comment by BrainSlayer** [comment]
ah btw. you can remove sputnik graphics etc. the company isnt existing anymore. i will remove it from dd-wrt as well

**Comment by the-j0k3r** [comment]
>i simply removed the manipulated string. thats a bad idea anyway. i show the copyright information in the selection area for the stylus preset. you will see it when its done. i have already written the code and now i'm just tested it on my devices. auto updates shall not be permitted anyway for security reasons. i have to update the stylus compiled code manually once there is a new one out

For inclusion in dd-wrt I agree, for these purposes of 3rd party not really as everything is manipulated anyway.

Copyrights for the css need to be included also and license which is MIT

@brainslayer

Also these are not to be referred to officially as stylus presets in any way shape or form, Stylus is a separate project Im unnafiliated with that, and this is my work, Stylus its an addon for the browser that facilitates such like projects like this one no more no less

https://svn.dd-wrt.com/changeset/47319 names all of them `somename.stylus`

'path src/router/kromo/dd-wrt/stylus`

should be

src/router/kromo/dd-wrt/dd-wrt-inspired-themes

styles names should be `somename.dd-wrt-inspired-themes`

This should be referred to as **dd-wrt-inspired-themes** if anything, please and thanks and the following added to the css headers, please.

```
## dd-wrt-inspired-themes
## © 2021 Style-it-themes - the-j0k3r
## License: MIT
## URL: https://github.com/style-it-themes/dd-wrt-inspired-themes
```

This commit https://svn.dd-wrt.com/changeset/47316

Should read `DD-WRT Inspired themes © 2021 Style-it-themes - the-j0k3r

https://svn.dd-wrt.com/changeset/47313

Not stylus. its `dd-wrt-inspired-themes`

https://svn.dd-wrt.com/changeset/47322

same, labels shouldn't read stylus at all.

and so on and so forth. Thank you

>ah btw. you can remove sputnik graphics etc. the company isnt existing anymore. i will remove it from dd-wrt as well

Sure, will do when its official, you can also update the remaining logos for hotspots with the provided ones from here, however wifidog logo is only for dark styles, light styles need a different image to be readable.
Currently all the default logos are indeed yuk. I see someone tried to submit new ones but never went anywhere.

See https://svn.dd-wrt.com/ticket/5193

**Comment by the-j0k3r** [comment]
Ping above edits =) thanks for understanding.

**Comment by the-j0k3r** [comment]
@BrainSlayer ping above edits =) thanks for understanding.

**Comment by BrainSlayer** [comment]
but you know that these are just folder names which are totally invisible in the firmware. so dont be pedantic by forcing overlong folder names in my dev tree.

**Comment by BrainSlayer** [comment]
and dashes are not allowed in variable names. i use the short variant. more important is the label which is shown in the gui and nothing else. and there is dd-wrt inspired styles and nothing else

**Comment by BrainSlayer** [comment]
![image](https://user-images.githubusercontent.com/7693971/132090173-c5b32478-256a-4f5b-aa47-bb9a16aedef5.png)

**Comment by BrainSlayer** [comment]
the inspired styles string etc. you want is too long. it doesnt fit

**Comment by BrainSlayer** [comment]
latest version

![image](https://user-images.githubusercontent.com/7693971/132091675-03e62795-784b-4637-815f-7e5e2a0ce76e.png)

**Comment by the-j0k3r** [comment]
@BrainSlayer

Dracula, Solarized Dark, etc is enough as names go, from options in select menu,

The correct name of the styles on select should be the same as the screenshot below.

![Capture](https://user-images.githubusercontent.com/31389848/132091757-4d96007c-7f72-44a4-8f50-5ab8d4c4eb87.PNG)

https://svn.dd-wrt.com/browser/src/router/kromo/dd-wrt/ddwrt_inspired_themes/solarized_darker.stylus?rev=47343

Not solarized darker, its dark. this matters somewhat because it supposed to match with the syntax highlighting names.

>  by forcing overlong folder names in my dev tree.

We can shorten that by removing `.stylus` from the theme names like

https://svn.dd-wrt.com/browser/src/router/kromo/dd-wrt/ddwrt_inspired_themes?rev=47343&order=name

Shouldnt the extension be CSS and not stylus?` themename.css` is what is standard for browsers, `.styl` is only recogized internally by the browser extension which you dont need or use.

Anyway I feel this request has been filled so will be closing soon.

I will make some updates to this theme so that by default the styling is as I prefer, since users cannot customize options.

Also note.

https://svn.dd-wrt.com/browser/src/router/kromo/dd-wrt/ddwrt_inspired_themes/dracula.stylus?rev=47343#L8
https://svn.dd-wrt.com/browser/src/router/kromo/dd-wrt/ddwrt_inspired_themes/dracula.stylus?rev=47343#L9

Can be removed from these, since there are no custom options to change fonts via the included dd-rwrt styles.

Lets see how it all looks in the end... Finally dd-wrt has pretty consistent styling everywhere. Until someone complains that theire internet explorer browser doesn't support half the css properties used.

Extra note

It would be a LOT LOT easier/faster and more efficient and make for smaller styles, just to change the :root values around and have a single static css files for these styles.

Thats how theming should be done via css in any case.

**Comment by the-j0k3r** [comment]
@BrainSlayer 

Also the checkbox width and height should be `.88rem` because that is what looks better atm youre using defaults which is way to big at 1rem

Ill make that default cause I wasnt intending to have these things fixed size without a way to change it after.

**Comment by BrainSlayer** [comment]
its no css. its css embedded html code which is generated. i choose the extension stylus since it was made with stylus and i need a unique file extension for implementing a file scanner. so the drop down menu gets automatic generated entries.

**Comment by BrainSlayer** [comment]
yes i know that just changing the root values would be enough. but only in theory. unfortunatly the style files differ also in other parts. but the internal fs compression does a good job. all files are 18kb in total

**Comment by BrainSlayer** [comment]
> @BrainSlayer
> 
> Also the checkbox width and height should be `.88rem` because that is what looks better atm youre using defaults which is way to big at 1rem
> 
> Ill make that default cause I wasnt intending to have these things fixed size without a way to change it after.

dont know what you mean. i did use the files as is. no modifications.

**Comment by the-j0k3r** [comment]
> its no css. its css embedded html code which is generated. i choose the extension stylus since it was made with stylus and i need a unique file extension for implementing a file scanner. so the drop down menu gets automatic generated entries.

In that case please use `.styl`  this wasnt made with stylus, misconception. 

Theres tow distinct stylus and only one is related here.

Stylus the browser extension

Stylus the programing language used on this project.

So `.styl` is the actual extension like shown on 

![Capture](https://user-images.githubusercontent.com/31389848/132092801-5a33f71c-f662-4133-a208-2624e977e2a6.PNG)

>unfortunatly the style files differ also in other parts.

They shouldnt at all, if they do, theres going to be issues.

**Comment by the-j0k3r** [comment]
> dont know what you mean. i did use the files as is. no modifications.

Here for instance.

https://svn.dd-wrt.com/browser/src/router/kromo/dd-wrt/ddwrt_inspired_themes/solarized_darker.stylus?rev=47343#L930
https://svn.dd-wrt.com/browser/src/router/kromo/dd-wrt/ddwrt_inspired_themes/solarized_darker.stylus?rev=47343#L931

**Comment by BrainSlayer** [comment]
its not modified. its default by stylus

**Comment by BrainSlayer** [comment]
> > its no css. its css embedded html code which is generated. i choose the extension stylus since it was made with stylus and i need a unique file extension for implementing a file scanner. so the drop down menu gets automatic generated entries.
> 
> In that case please use `.styl` this wasnt made with stylus, misconception.
> 
> Theres tow distinct stylus and only one is related here.
> 
> Stylus the browser extension
> 
> Stylus the programing language used on this project.
> 
> So `.styl` is the actual extension like shown on
> 
> ![Capture](https://user-images.githubusercontent.com/31389848/132092801-5a33f71c-f662-4133-a208-2624e977e2a6.PNG)
> 
> > unfortunatly the style files differ also in other parts.
> 
> They shouldnt at all, if they do, theres going to be issues.

but they do. check it by yourself what stylus generates

**Comment by the-j0k3r** [comment]
> its not modified. its default by stylus

Again with stylus, the default option dont come from stylus they come from this theme.

See

https://github.com/style-it-themes/dd-wrt-inspired-themes/blob/3c289cd6483b5350a1d4347d2e0fa6bb9bc58947/dd-wrt-inspired-themes.user.styl#L13-L42

If I had some warning you were going to do this so fast commit into repo, I would have time to adjust the values and make an update, which is my intention because for official inclusion things have to be a certain way, else they will present issues in some cases

As is consider my suggestions it will offer best results across OS's font sizes etc.

Ill be making updates asap.

**Comment by the-j0k3r** [comment]
@BrainSlayer 

in order to iron out the kinks here it is update 3.2.0 has been pushed. any css should be compiled from these.

https://github.com/style-it-themes/dd-wrt-inspired-themes/commit/36da85f02ccb97c9d9131ed3947119b2f68a04db

Again please note the update procedures for your install of this theme as noted in the readme.

Theres two ways to update the style now (since you edited your style to add your IP) the auto-updates are blocked. this is by design thats outside our control/

1) force update style
2) re-edit IP's

or 

1) Edit the style via the extension

![edit](https://user-images.githubusercontent.com/31389848/132093701-8cf1b622-9dc8-45d6-8d27-489e4bb6f34b.gif)

2) copy and paste the changes into the same area as the commit above

On another note, do the theme files already include the speedchecker, oid, iplookup etc stylesheets?

I dont have time right now, but the css should be same for all styles.

I dont mind doing it if you dont mind waiting.

Earlier you said

>    unfortunatly the style files differ also in other parts.

Im unsure what differences these are, there should be 0 differences except the colors.

**Comment by the-j0k3r** [comment]
I can take requests for new color schemes to be added in individual new tickets please.

**Comment by BrainSlayer** [comment]
speedchecker and mac oid lookup etc are external sites. they cannot be modified from the os itself. for the 401 error site. first you are using outdated strings. the hint with the root login is not existing anymore since its 15 years old. people should know it now. additing a additional copyright string for the theme is not neccessary from my point of view. basicly i dont like that. it should be noted on a more special info place, but not on a functional page

**Comment by BrainSlayer** [comment]
and there is another bug. your style replaces 404 file not found with 401 authorization required

**Comment by BrainSlayer** [comment]
in addition the "info" character before this string is a invalid html character.  use `"&#9432;"`
![image](https://user-images.githubusercontent.com/7693971/132094701-5dc90239-a88d-46cc-bf85-1f24b002c12d.png)

**Comment by BrainSlayer** [comment]
and just for your information. the 0,88rem checkbox size has no effect in chrome/windows

**Comment by the-j0k3r** [comment]
>speedchecker and mac oid lookup etc are external sites. they cannot be modified from the os itself

Yes, there is that,

> and there is another bug. your style replaces 404 file not found with 401 authorization required

My style, only styles the 401 page when you dont enter a password or valid password, 

I would need to see what the differences between the dd-wrt css for both 401/404 pages before I can actually see what the issue is.

Im overriding the 401 page default dd-wrt css when this page is generated and hacking the redesign ontop of that css, not instead of.

So to some extent, this theme as is and the css needs to have a base framework that is used in order to be extended/modified
For instance, you go and select the brainslayer built in theme, and then use this ontop, you will see it looks awful, thats because the brainslayer css differs a great deal for the blue ddwrt style.

I suspect by loading the compiled css from here the results wont be equal to using this project as 3rd party. But will see.

Now to try and generate a 404 page and see if the css that needs to be overriden is exact same only with different messages
if it is, the only thing to do, if you insist on this course of action will be NOT to include the 401 page redesign/

>and just for your information. the 0,88rem checkbox size has no effect in chrome/windows

Maybe some values need to be adding `!important` so that they are loaded, if it does, easy fix.

> the hint with the root login is not existing anymore since its 15 years old.

Well, this message existed when developed this theme and not 15 years ago, this was done 8 months ago, and then the message read the same.

Will fix though. I alwas thought it was silly to tell random ppl that probably tried to login and failed and are not the owner what the username for ssh was.

**Comment by the-j0k3r** [comment]
OK re 401 404

Yes, DD-WRT doesnt have specific 401/404 css, its just injects the page contents depending on 401/404

If you add a specific bg color for the 404 page, I can target them specifically as is Im picking at generic hardcoded values like `[bgcolor="#cc9999"]` is commons to both pages.

see 404 what it allows me to pick at this is as I said.

![Capture](https://user-images.githubusercontent.com/31389848/132143452-69e84457-f644-42e5-9043-1f5217695fb3.PNG)

https://github.com/style-it-themes/dd-wrt-inspired-themes/blob/9165e026d4550e41e8cfb53afde2f2de9406ce32/dd-wrt-inspired-themes.user.styl#L438

So the bug is caused because as I said on https://github.com/style-it-themes/dd-wrt-inspired-themes/issues/1#issuecomment-912377668

>DD-WRT uses a oversimplified number of CSS classes, I had to pick at other inline portion to be able to target specific portions in order to be able to distinguish between certain elements like e.g. this [name='add_button']:not([onclick*='_add']) a long dance is done all over this project to make this style possible.

Its not just classes, hardcoded colors makes doing a pure css style that looks good really hard, this is the reason behind for instace you load any built in style from dd-wrt choose dark, and not all areas of the style will be dark, e.g. help pages and other dialogs.

It was really not simple job and in order to improve and make styling with css, dd-wrt needs to add more specificity so anyone can style something specific without affecting the other. This was glossed over on my first post.

Unless you add different specificity, your option is NOT to include the 401 redesign.

From this style, the fix is easy in that case, first Ill make that option off as default, and add a readme not about the issue, since I cant change dd-wrt design, only you can, if in a hurry or wait until I can make contributions to dd-wrt to improve the limitations of the design.

**Comment by the-j0k3r** [comment]
>and just for your information. the 0,88rem checkbox size has no effect in chrome/windows

for some reason no browser is respecting these settings anymore when lower than 1rem **while using dd-wrt,** it works for instance on my github style

![edit](https://user-images.githubusercontent.com/31389848/132145089-057f09e1-0c0d-4bce-936f-35db24e9e7c2.gif)

I have no idea why this is, while inspecting values there is nothing showing up that overrides this in any manner.

More investigation needed.

**Comment by Mile-Lile** [comment]
I just tested these new styles within nightly ddwrt r47371... works smoothly... I like them very much ubuntu and matrix are great but for eveyday usage will stick with Material Darker... Thx BS and the-j0k3r for your great work.

**Comment by BrainSlayer** [comment]
i fixed the 401 issue by simply auto modifying the css content with the correct strings required

**Comment by BrainSlayer** [comment]
> > and just for your information. the 0,88rem checkbox size has no effect in chrome/windows
> 
> for some reason no browser is respecting these settings anymore when lower than 1rem **while using dd-wrt,** it works for instance on my github style
> 
> ![edit](https://user-images.githubusercontent.com/31389848/132145089-057f09e1-0c0d-4bce-936f-35db24e9e7c2.gif)
> 
> I have no idea why this is, while inspecting values there is nothing showing up that overrides this in any manner.
> 
> More investigation needed.

its windows. they use the standard checkbox model. you cannot compare this with linux all the time

**Comment by the-j0k3r** [comment]
> i fixed the 401 issue by simply auto modifying the css content with the correct strings required

You fixed it for the built in styles or will I be able to style independent pages without conflict in this project.
It would be nice if I could have something unique enough in some areas such as this so I can do targeted styling without conflicts, if its not done already, please, pretty please? just a different bg color would be enough or something else that unique enough.

Also I have a request of same nature for you dd-wrt, If you could add something unique enough for these two fieldsets

Overclocking/Gui style

![Capture](https://user-images.githubusercontent.com/31389848/132185949-a7b1fb09-34dc-44fe-9285-4bcd99dd8ef6.PNG)

This + the 401/404 pages would be of great assistance to me and this project.

>its windows. they use the standard checkbox model. you cannot compare this with linux all the time

Its not Windows afaik, else, I wouldnt be able to make option work on my github style, the optionis dead for anything lower than `1rem` only on dd-wrt afaict, every other website this works perfectly. WHY idk. but it is what I observe.

**Comment by the-j0k3r** [comment]
>I just tested these new styles within nightly ddwrt r47371... works smoothly... I like them very much ubuntu and matrix are great but for eveyday usage will stick with Material Darker... Thx BS and the-j0k3r for your great work.

@Mile-Lile 

Im glad you like it, however a reminder, there are limitations in styling areas that the built in styles will never reach, so you will see some areas like speedchecker, oid, iplookup and other places that wont match the selected style.

This is a limitation of css styles because you cannot target specific domains, this limitation doesnt exist when using this project.

I will be testing the built in styles, to see how they differ and other details in specific dialogs/pages but of course I will never use the built in styles because of these limitations, I prefer consistent styling, and one of the main reasons why this project exists.

**Comment by BrainSlayer** [comment]
> > i fixed the 401 issue by simply auto modifying the css content with the correct strings required
> 
> You fixed it for the built in styles or will I be able to style independent pages without conflict in this project.
> It would be nice if I could have something unique enough in some areas such as this so I can do targeted styling without conflicts, if its not done already, please, pretty please? just a different bg color would be enough or something else that unique enough.
> 
> Also I have a request of same nature for you dd-wrt, If you could add something unique enough for these two fieldsets
> 
> Overclocking/Gui style
> 
> ![Capture](https://user-images.githubusercontent.com/31389848/132185949-a7b1fb09-34dc-44fe-9285-4bcd99dd8ef6.PNG)
> 
> This + the 401/404 pages would be of great assistance to me and this project.
> 
> > its windows. they use the standard checkbox model. you cannot compare this with linux all the time
> 
> Its not Windows afaik, else, I wouldnt be able to make option work on my github style, the optionis dead for anything lower than `1rem` only on dd-wrt afaict, every other website this works perfectly. WHY idk. but it is what I observe.

your styles will work anyway since they override it again. but its not possible to automodify the styles provided by the plugin since its injected without any care what the os does

**Comment by BrainSlayer** [comment]
> > I just tested these new styles within nightly ddwrt r47371... works smoothly... I like them very much ubuntu and matrix are great but for eveyday usage will stick with Material Darker... Thx BS and the-j0k3r for your great work.
> 
> @Mile-Lile
> 
> Im glad you like it, however a reminder, there are limitations in styling areas that the built in styles will never reach, so you will see some areas like speedchecker, oid, iplookup and other places that wont match the selected style.
> 
> This is a limitation of css styles because you cannot target specific domains, this limitation doesnt exist when using this project.
> 
> I will be testing the built in styles, to see how they differ and other details in specific dialogs/pages but of course I will never use the built in styles because of these limitations, I prefer consistent styling, and one of the main reasons why this project exists.

there is always a dirty trick to reach that approach. simply by giving the style as argument to the oid / speedchecker etc call and injecting it from the remote server. but rome wasnt build in one day. right?

**Comment by the-j0k3r** [comment]
>there is always a dirty trick to reach that approach. simply by giving the style as argument to the oid / speedchecker etc call and injecting it from the remote server. but rome wasnt build in one day. right?

right! =)

When rome is built those areas, the specific css will be needed in addition. Not a big deal, its pretty simple to compile that sass to css, it may need other work this side.

>your styles will work anyway since they override it again. but its not possible to automodify the styles provided by the plugin since its injected without any care what the os does

So its a definite no to adding specific classes/id's or something so I can target specific areas? Or is this like rome? =)

Will see only how 401/404it works when I upgrade the build that has all these changes upstream.
I see breaking changes in the design of this style when that happens Im sure because Im targeting a generic area thats reused. To early to know for me.

**Comment by the-j0k3r** [comment]
@BrainSlayer 

Ive pushed some updates that you may want to include as its bug fixes.

See https://github.com/style-it-themes/dd-wrt-inspired-themes/commit/ebd485be6cbd408edcad4009d2923990326aab1f#diff-09915394eeaa47b9e6003161cc84a54a1148ae5cf944c0f4a7e2f14526a96d64L1698-R1741

there are other changes that you may want to consider in other commits.

**Comment by BrainSlayer** [comment]
will merge it in next build round

**Comment by egc112** [comment]
Guys congrats on this nice addition, have been away for a few days but just tested it and it looks very nice indeed

**Comment by the-j0k3r** [comment]
@egc112 You mean the built in versions or this project?

**Comment by egc112** [comment]
The built in version in DDWRT

**Comment by the-j0k3r** [comment]
I haven't yet, but will eventually to see how it compares to this, minus the expected limitations of the built in version at this time.

Feel free to try this project though, its far more flexible and customizable on the fly.

**Comment by egc112** [comment]
I  definitely will but I am going away for a few weeks so that has to wait, again thanks for this nice project

**Comment by the-j0k3r** [comment]
You're welcome and enjoy your getaway. Be safe out there, dont forget your hazmat suit =)

**Comment by the-j0k3r** [comment]
3.2.2 has been released with an important bug fix and other tweaks and fixes, something slipped in while fiddling with 401/404 reported issue, due to faulty nesting. My bad.

Still todo

- [ ] figure out why DD-WRT doesn't like checkbox/radio custom width/height lower than `1rem` when all other sites that I use same custom input works 100%
- [ ] need to update DD-WRT and redo my 401 page redesign and try to make the redesign work for all 4xx pages
- [ ] add more color schemes

**Comment by BrainSlayer** [comment]
you dont need to care about your 401 redesign problem. the integrated version handles this now very well. otherwise i need todo custom tags for each error page to let you handle it with stylus. i will now review your changed and integrate them for next version

**Comment by BrainSlayer** [comment]
please note certain errors in your style. i fixed one already. this one is left
![image](https://user-images.githubusercontent.com/7693971/132393363-d646d91b-c0f0-4d25-9a49-2eaf52cdb40f.png)

**Comment by BrainSlayer** [comment]
but biggest issue is that the latest version does not work at all anymore. this is how it looks
![image](https://user-images.githubusercontent.com/7693971/132393829-3b59f3a9-7e06-46ac-8b8a-b7e08fd636b2.png)

**Comment by the-j0k3r** [comment]
> otherwise i need todo custom tags for each error page to let you handle it with stylus.

If you ignore my plight what is the point of any of this?

I need to be able to address theming/design in some way, here with my project and dd-wrt, if you deny me a way to handle special cases.

>please note certain errors in your style. i fixed one already. this one is left

IDK what you mean, you should NOT alter any code whatsoever.

The error you see are linting issues, stylelint is a linter, because the linter DOES NOT support stylus lang, by fixing the issues that are not issues you are fixing what isnt broken. Its a linter limitation nothing else.

Please ignore linting errors. you can safely disable the linter and silently ignore the noise.

>but biggest issue is that the latest version does not work at all anymore. this is how it looks

As above, dont fix what isnt broken and it will work.

Please consider allowing me to pick css for special cases like the 4xx pages cases, the gui styles/overclocking fieldsets etc, so I can design things better for both dd-wrt and here. Its a small request considering how hard I have to work to hack and pick at very generic css that gets reused and only causes headaches and bugs that could be avoided for anyone wishing to do nice things for dd-wrt themes.

Please and thanks in advance for your consideration and support to support unique something in some areas so they can be redesigned via css.

Thanks again.

**Comment by the-j0k3r** [comment]
Also if you want a similar theme for stylus I also make one, see https://github.com/style-it-themes/stylus-wardrobe

**Comment by BrainSlayer** [comment]
for the error pages i dont have yet i idea to proper handle this. i may introduce custom tags instead of <h4> for instance. but that also means i have to alter all existing css styles to handle them too. i'm open for suggestions. btw. latest version is running in my internal builds now

**Comment by BrainSlayer** [comment]
i found one thing. if a button is greyed out (see the autorefresh button). you are mostly unable to read it since the font color is too dark. see button on the bottom of this screenshot. the same issue exists for the signal quality bar
![image](https://user-images.githubusercontent.com/7693971/132466409-8c95fd4b-6d00-4d54-8df0-c96d09cb798b.png)

**Comment by the-j0k3r** [comment]
Hello again, let me have a sip of ☕ =)

>or instance. but that also means i have to alter all existing css styles to handle them too. i'm open for suggestions

The error pages, all I would need is a unique enough `bgcolor` or a unique `id="40x`

ATM the `bgcolor` is generic and reused, there is nothing unique.

I haven't looked at all the internal themes, I will try to put some time aside today for this.
If I had to guess none of the previously existing internal themes handled this at all, so if my supposition is right no chnages to them would be required.

The fieldsets are also generic, so I cant really target a specific one, do some magic to it without breaking another on some other page, the most pressing ones are the overclocking one and the gui-styles ones.

>i found one thing. if a button is greyed out (see the autorefresh button). you are mostly unable to read it since the font color is too dark. see button on the bottom of this screenshot. the same issue exists for the signal quality bar

Thanks, I'll have a look and see what can be improved here contrast wise. the signal quality etc bars are going to be more problematic especially for the internal versions of this, because users cannot use the options provided in style to tweak generated colors. I had to subdue these because of `the-matrix` preset.

<btw. latest version is running in my internal builds now

What was the issue? You upgraded to 3.2.2 by forced update and forgot to enter IP.s? Something else? Just curious.

I could try to use a regex instead of IP's for this so that users dont have to do anything and auto-updates aren't blocked by local edits. I wonder if anyone uses some other way, like using domain names and access router that way, so those users would need to edit anyway. Let me put some time aside for this also.

Also feel free to star the project anyone. =)

**Comment by BrainSlayer** [comment]
issue. ahm i ignored the shown errors, used it as is. modified the style element for the error page needs (current solution for me) and done. i will think about the bg solution usually i encode the error code somewhere in the color in a invisible way

**Comment by the-j0k3r** [comment]
OK some updates done and version 4.0 has been released.

-Fixed contrast in bars text
-Fixed contrast in auto-refresh button (I would prefer to have left it as was, drawing user's attention to disabled buttons is not great design, none-the-less contrast is slightly improved.
-Some more fixes/updates that will need to be pushed to DD-WRT
-Added IP regex matching, so you no longer need to edit theme and add your own IP's and when I push updates, eventually you will notice that its been auto-updated, this is a better, I hope code design choice. We will see. ;)

This is great but if you have specific setups since ALL valid IPV4 blocks are matched it may style local servers or web interfaces other than DD-WRT interface. I dont use torrents or other built in services that have some web interface outside dd-wrt so any such web interfaces would have been affected in some way in any case as long as they use same IP, cant do anything about that and not sure if there is a solution for such cases.

The readme has been updated and also added info about inclusion of the static themes

Do force update and let me know how that regex treats you =) I hope

> i will think about the bg solution usually i encode the error code somewhere in the color in a invisible way

Thanks. I really really beg for changes in some key areas like that so that conflicts are not encountered, I realize its simpler the way its done, but it does indeed make CSS styling at this level somewhat harder or impossible depending on what the target is.

>modified the style element for the error page needs (current solution for me) and done

The option for the redesigned page is OFF by default now, this triggers a basic no hack simple redesign that doesn't affect unrelated error pages, but it looks in comparison like ass to my intended design choice for a modern error page.

On an unrelated note I have noticed some bugs in DD-WRT, will try to update my build from 256 to newer when I can, but because of COVID and everyone working from home, I can only do upgrades at some specific times when Wireless in not being used.

**Comment by the-j0k3r** [comment]
OK had a unexpected break latest build installed.

So this...

![Capture](https://user-images.githubusercontent.com/31389848/132552717-f11facb4-c9ff-4ca8-b734-5a178bc3c63b.PNG)

The title feel free to make it simply `DD-WRT Inspired themes`, the rest could be some magic label after the drop down select menu like the above explanation of some range of some settings

Like e.g. 

```
-- DD-WRT Inspired themes ------------------------------------------------------------------
|                                                                                          |
|   Theme    [ some title  ^ ]                        © 2021 Style-it-themes - the-j0k3r   |
|                                                                                          |
--------------------------------------------------------------------------------------------
```

And the copyright can be subdued is you like. opacity of `.7` would be OK

I noticed that the themes dont reach the help menus and such, why would this be? And can it be fixed in dd-wrt?
It kinda burned my retinas on here. =) wasn't expecting it not to reach these areas.

https://IP/About.htm
https://IP/help/HManagement.asp -- this is help pages
https://IP/Wiviz_Survey.asp

The 400 error pages need a couple of tweaks it needs a space and maybe one less `!`? idk where 2 are coming from.

![Capture](https://user-images.githubusercontent.com/31389848/132560314-2b3b853a-a764-4204-b74a-0cd894c75729.PNG)

https://github.com/mirror/dd-wrt/blob/08e8bdee001c907698805026a8a7bea82cd7ab48/src/router/httpd/httpd.c#L487

```diff
-send_error(conn_fp, 0, 401, "UNAUTHORIZED", header, "Authorization required. Wrong username and/or password!");
+send_error(conn_fp, 0, 401, "UNAUTHORIZED", header, " Authorization required. Wrong username and/or password");
```

![Capture](https://user-images.githubusercontent.com/31389848/132560803-3a63ffaf-3264-4d7e-ae58-1e0795adb450.PNG)

https://github.com/mirror/dd-wrt/blob/08e8bdee001c907698805026a8a7bea82cd7ab48/src/router/httpd/httpd.c#L1268

The Not found text should be CAPS, essentially whatever page it is, after 400, 401,404 -> CAPS. thx.
```diff
-send_error(conn_fp, noheader, 404, "Not Found", NULL, "File %s not found.", file);
+send_error(conn_fp, noheader, 404, " NOT FOUND", NULL, "File %s not found.", file);
```
idk where the rogue exclamations points are coming from. Cant say I looked that hard.

IDK if these apply

https://github.com/mirror/dd-wrt/blob/08e8bdee001c907698805026a8a7bea82cd7ab48/src/router/httpd/httpd.c#L1040-L1053

`Bad Request` -> `BAD REQUEST`

and so on, make sense for consistency?

There is another error on https://IP/Status_Internet.asp (sorry for bringing it up here)

![Capture](https://user-images.githubusercontent.com/31389848/132556475-79c70d48-8253-4c01-bbac-da13fc7de6b9.PNG)

re: https://svn.dd-wrt.com/ticket/7460, so the fix causing new error, in console, nothing serious I think but there it is.

Another error in  https://IP/Wireless_Basic.asp

![Capture](https://user-images.githubusercontent.com/31389848/132557819-fa9188cc-eca1-4539-809f-eeec124929da.PNG)

https://developer.mozilla.org/en-US/Optimizing_Your_Pages_for_Speculative_Parsing

&& that link is dead but this works https://developer.mozilla.org/pt-BR/docs/Glossary/speculative_parsing its in English so clearly someone at Mozilla is like Mozzarella mk.

Other than that and until Rome has been built to reach speedchecker/iod etc its looks very nice
Thank you so much for everything so far.

**Comment by the-j0k3r** [comment]
Also a grammar minor thing, I saw this commit from treat to threat typo fix recently on tracker.

https://github.com/mirror/dd-wrt/blob/08e8bdee001c907698805026a8a7bea82cd7ab48/src/router/httpd/httpd.c#L938

```diff
-send_error(conn_fp, 0, 400, "Bad Request", NULL, "Illegal filename. (filename will threat local filesystem)");
+send_error(conn_fp, 0, 400, "BAD REQUEST", NULL, " Illegal filename. (filename will threaten local filesystem)");
```
always space before the first word so it doesnt look glued to the info icon.

If it were Git instead of SVN I would easily make a pull request for these adn whatever else I found. As is youre the expert at this and you know what is what better than me.

I can try make a diff of that file.

**Comment by the-j0k3r** [comment]
I released version 4.0.1 which disables the error page redesign fallback design and original design.

The built in redesign as above what I cant style due to uniqueness issue, is becoming a nightmare for me.

The regular gui styles use the OLD design and that is whay this redesign for that.

![Capture](https://user-images.githubusercontent.com/31389848/132567157-022c462f-9526-4883-a43f-10440f59eb24.PNG)

when you use old dd-wrt gui-styles and you turned off the 401 redesign option this is what it did. see the else 

https://github.com/style-it-themes/dd-wrt-inspired-themes/blob/5c6fe87f2bd122dfef498f90721b793e6691b477/dd-wrt-inspired-themes.user.styl#L504-L522

![Capture](https://user-images.githubusercontent.com/31389848/132567487-321ad9bc-6965-4007-8054-355849bf0230.PNG)

It was a sloppy ugly alternative, but..... that was the best way I found with the limitations.

As I see it, even if you add unique strings and I style error pages individually it will show double text when users have the now internal version dd-wrt inspired themes of this project enabled ontop then this is what you would see.

![Capture](https://user-images.githubusercontent.com/31389848/132568102-63333cd2-c806-4c79-b44c-2f62b8b9d03f.PNG)

So literally the ONLY solution is for ALL the internal dd-wrt themes to use the redesigned pages and I can remove that option from here fully its impossible to determine which styles are in use on DD-WRT and therefore cannot do anything here in this style about it.
So including redesign for all internal themes is the only way forward.

**Comment by BrainSlayer** [comment]
you mean force of use the themes?  that makes no sense. there are even incompatible designs like xirian, kromo and brainslayer style.

**Comment by the-j0k3r** [comment]
I meant the 40x,whatever pages redesign, not the complete themes, no internal gui-styles themes, and least of all those you mentioned, none touches these areas not even anything remotely close, so there wont be any conflicts.

**Comment by BrainSlayer** [comment]
then i need to split the css for the error redesign. and is it neccessary to force the redesign? i dont think so. i know it looks nice. but you missed something. there are indeed people using dd-wrt which are visually handicapped. they need more contrast oriented designs and simple letters

**Comment by BrainSlayer** [comment]
and can you make a break with updating :-) redoing the css files is a anoying work each time

**Comment by the-j0k3r** [comment]
> then i need to split the css for the error redesign. 

No you dont, the css for the error pages can be simply added to all those other old gui-styles.

>and is it neccessary to force the redesign? i dont think so

The reason I did the redesign to begin with is because no matter what.

Now because of how its done internally, users of this project (and myself) are penalized.

>and can you make a break with updating :-) redoing the css files is a anoying work each time

I also have a solution for that, but we should discuss it, only using one file with the classes and the root values are untouched, and using @import for the file with css classes so only ONE file updating is needed.

Also, what choice do I have with the issues you report? or some bug?

After 4.0.2 there shouldnt be anymore changes, unless upstream does something to force me to fix something.

**Comment by BrainSlayer** [comment]
if i have to add it to all other styles, it is a "split". and i have to rewrite the whole css handling code first, since i have to modify the error css for each error page call. 

ans no using one file is no solution. make a test by yourself. its not just the root values which are touched depending on the theme. there are alot of other rgb values within the file which are indiviually different. see screenshot

![image](https://user-images.githubusercontent.com/7693971/132625430-4cfae2a3-6429-43d5-a52a-34fa29360e89.png)

**Comment by BrainSlayer** [comment]
and its not about the choice. as you see i found own solutions for handling it. (error pages etc). i did not report that much. my main problem all the time is that once i just try to edit a single value in your style (like reenable 401 error support), stylus says the style has errors and turns them into useless waste. i dont know what fucked up plugin this is, but the internal editor seem to have a strange behaviour. i dont know how to handle that mess. and using a external editor doesnt work either. because i cannot import styles from the local filesystem. the browser just shows the text if i drag and drop it, but stylus doesnt catch it

**Comment by the-j0k3r** [comment]
Here is httpd.c diff @brainslayer do check the diff first, should be OK though.

https://gist.github.com/the-j0k3r/c79546c86c426a18756661df7d6974b1/revisions

shows changes to error messages.

> i dont know what fucked up plugin this is, but the internal editor seem to have a strange behaviour.

IDK what you mean, any errors are linting errors and they can be ignored. I never had an issue otherwise and I been using this plugin for many years.

>main problem all the time is that once i just try to edit a single value in your style (like reenable 401 error support), stylus says the style has errors and turns them into useless waste

I doubt that, I do this ALL the time, even with editor open, Solution, close the editor when changing options. Else if you have some error paste it here so I can see and assess where issue is.

You know, there are many annoyances, Im annoyed youre annoyed and yet things have to get done somehow.

Ill see about doing the internal old styles adding the required error css.

**Comment by the-j0k3r** [comment]
updated diff, sorry about that

https://gist.github.com/the-j0k3r/c79546c86c426a18756661df7d6974b1/revisions

scroll down to see all changes.

**Comment by the-j0k3r** [comment]
And Again, updated diff, I cant believe Im so stressed out so early in the morning.

Sorry. should be all OK now with diff and messages.

**Comment by BrainSlayer** [comment]
i commited it already. thank you

**Comment by BrainSlayer** [comment]
i need to rework the string handling anyway in that piece of code, for proper translation into local languages

**Comment by the-j0k3r** [comment]
> i need to rework the string handling anyway in that piece of code, for proper translation into local languages

Sure.

If I may suggest something.

I see many many duplicate messages, wouldn't it be better on this rework if the messages were made into variables that could be called in respective places?

I'm not familiar with C, but generally speaking with other languages it shouldn't be an issue and much cleaner simpler saving the bits weherever possible.

I would name the vars after the error type: 400_blahblah, 404_blabla and so on?

ATM Im trying to grab a clone of my fork of the mirror, SVN just is not as contributions friendly like Git is, and this process for some reason is being a total fail today. I think it broke GitHub.

**Comment by BrainSlayer** [comment]
see my last commits. this is what i was talking about with translation work etc. this work (which is already finished now) has the benefit that all strings get combined and deduplicated. so we have no a central point for all strings.

**Comment by BrainSlayer** [comment]
yes you can just use the mirror. but its really just a auto generated mirror from my svn. i have a script running on my server which does the job updating it. i can take your changed as simple git patch then. for me using svn is much simpler. simple commands etc. i'm only working and programming on commandline and i do not use gui's and other helpers. so a simple and fast repository management is the goal and git is anything else but simple from commandline. and finally the svn is now 15 years old. its historic.

**Comment by the-j0k3r** [comment]
I understand, I work on command line also, but for visually checking for typos and because sometimes 4 eyes are better than 2 things are easier to spot that way.

IDK, apart from under the bonnet commands I use maybe 4, like `git commit -m "message"` `git push`  maybe interactive rebases when upstream changes causes conflicts with modded files etc. But yes, totally get your stance.

I havent used SVN since maybe 10 years or more, and making contributions to 3rd party projects has always been a pain in the backside, especially conflict resolution which Git makes simpler imo for simple conflicts. Not so when you own or have write privs. Not that I want any =), then yes, simpler is better. depending on how individuals work.

> i can take your changed as simple git patch then

thanks for that indeed helpful to know You dont mind that.  Will ping you when I have actual work ready for revision/merge.

**Comment by BrainSlayer** [comment]
svn works in the same way if you are just commiting. svn commit -m "message". done

**Comment by the-j0k3r** [comment]
To add to the previous issues reported, here is a new one.

 the spacing between DD-WRT Inspired themes © 2021 Style-it-themes - the-j0k3r
and
CIFS Automount fieldsets is not same as the others.

![Capture](https://user-images.githubusercontent.com/31389848/132685098-fc5293fc-e9d5-4b64-9169-080828ebf0b7.PNG)

Its missing a br between

![Capture](https://user-images.githubusercontent.com/31389848/132686072-fd3f7796-37d2-4c4d-b990-eb7fba59fa16.PNG)

All others are pretty consistent.

**Comment by BrainSlayer** [comment]
right. i will fix it this evening at home

**Comment by the-j0k3r** [comment]
>ans no using one file is no solution. make a test by yourself. its not just the root values which are touched depending on the theme. there are alot of other rgb values within the file which are indiviually different. see screenshot

This is easily solved from my end, I see I used a hand full of `rgba(BG, .075)` and so on, not many at all., so I turn these into CSS vars and done.

No big deal, + it means that the included styles from here can be a little smaller.

**Comment by BrainSlayer** [comment]
its not much smaller than you think. the hand made (modified) filesystem compression algorithm is very efficient. if i pack all together with tar.xz i get 18 kb. my filesystem stores all the stylus file in 16kb. a single file with xz is 17kb
so. yes i can bring it to 15.5 kb

**Comment by the-j0k3r** [comment]
Well Ive added the CSS vars so separation and @import of the CSS portions will give you more savings I hope.

I bet with that you can get down to single digits per style,

4.0.4 has been released and you should automatically get updated without interaction, stylus checks for updates every 24 hours. that is, if you're running anything from 4.0.0 and up.

That said, there is little rush to update the CSS files, I'm happy to help when I have time.

This should be now all quite stable and bug free, except for any eventual nitpicks or inclusion of more color schemes (if anyone wants others)

I want to fix the old styles upstream, but I really in due time. Ive updated the readme which explains which styles are compatible with this working together, but the incompatible ones will likely never look as good even after fixes, though I hope to make them less of an eye sore.

And again, I did reports quite a few issues on previous comments here, when you have time please have a read.

have a nice evening, and relax. I sure as hell need some alcohol right about NOW!!

🍻 Cheers!! Here's to a brighter future.

**Comment by BrainSlayer** [comment]
most of these styles are more than 12 years old. rome wasnt build on one day and i'm just happy for any modern contribution here. take the time you need, but there is no hurry or force. just do what you want to do

and yes, there is a brigher future. somewhen. we all what we are talking about. i'm also running a concert venue :-)

**Comment by the-j0k3r** [comment]
> most of these styles are more than 12 years old

One of the many reason why I did this for myself =)

>rome wasnt build on one day and i'm just happy for any modern contribution here

With your help, we need to improve the limitations of DD-WRT generic classes, so things can be targeted without affecting others for one.
For another, the inline style colors need to be replaced with classes, margins/paddings etc its not too bad and sometimes there isn't another way. The ancient designs pre CSS need to die already. DD-WRT is not terrible at this, I compare it to say Wikipedia, there trust me, hell is a kinder place for anyone doing styles for that site let me tell you =).

We will get there, of that I have no doubt.

>we all what we are talking about. i'm also running a concert venue :-)

During COVID I bet that's fun ;)

On an unrelated topic. If you like, you could join my discord server (link on readme) I promise I wont be bugging you 24hours a day. :p (famous last words). May come in handy, is all. have a good weekend now.

**Comment by BrainSlayer** [comment]
the main problem is, i hate html, css and all that mess. its definitly not my programming language.  so i'm definitly not the one who can do it right and in the most clever way. for me it would be helpfull if you just take one of the asp files. and show what has to be changed. but in a way that i can follow the scheme and can do all the rest of the adaptions in the html and cgi code. and we should do this step by step. if you rewrite everything from scratch i'm lost, because the generated html code by cgi alone is massive


yeah. fun. ahm. if you think that loosing money and all your hopes and dreams is fun,

will check the discord. never used it. every type of person uses a different chat system here, by desktop is flooded with online services :-)
![image](https://user-images.githubusercontent.com/7693971/132809718-fedfb87d-7a29-4783-8299-dc308ee9e674.png)

**Comment by BrainSlayer** [comment]
the invitation code for the discord channel in your readme is invalid

**Comment by BrainSlayer** [comment]
anyway. to allow me to keep the current styles up to date, can you please reenable the 401 error page code. otherwise converting them to the current style format will create alot of work each time. i do this by hand every time

**Comment by the-j0k3r** [comment]
> anyway. to allow me to keep the current styles up to date, can you please reenable the 401 error page code. otherwise converting them to the current style format will create alot of work each time. i do this by hand every time

Ah balls, I forgot about that Will re-add in a minute or so.

>the main problem is, i hate html, css and all that mess. its definitly not my programming language. so i'm definitly not the one who can do it right and in the most clever way. for me it would be helpfull if you just take one of the asp files. and show what has to be changed

Sure, its pretty simple, I dont do asp/cgi etc but I can ready it fine, one I see some example we can test it out.

Here is an invite code https://discord.gg/ayBbe3UE in meanwhile. 

Nice pic btw, I see the BrainSlayer silhouette there. =) 

>yeah. fun. ahm. if you think that loosing money and all your hopes and dreams is fun,

What hopes? What dreams? What money? 

If its that bad... get the hell out mate.

**Comment by the-j0k3r** [comment]
Closing this now has its been fulfilled. Thanks for playing, discussions can continue for sure.

related https://github.com/mirror/dd-wrt/pull/44 for merging upstream

**Comment by BrainSlayer** [comment]
the 401 page is still disabled. cannot merge

**Comment by the-j0k3r** [comment]
> the 401 page is still disabled. cannot merge

Please look at this https://github.com/mirror/dd-wrt/pull/44 all the updates are there, I have some more things to add, but can be a bit later

Is that OK or you prefer something else?

The option is disabled by default but everything is there, but it can be enabled, in any case. By using the style option menu. Almost everything. Style should be at version 4.0.9 due to some errors on my part.

**Comment by the-j0k3r** [comment]
@BrainSlayer ping, when you have a moment please ping me on my discord server. No rush.

**Comment by BrainSlayer** [comment]
need to finish some work here. may take some hours

**Comment by the-j0k3r** [comment]
np Im going offline for a bit and come back around 17.00 ish
